### ISSUE TITLE
Implement proper resolution fix

### ISSUE THREAD

**Issue by Banz99** [rebtd7/FF13Fix#10]
Hey, I've been looking at how the game works through Ghidra and came to the conclusion that while we can't currently know why the game decides that it should treat 2560*1440 as 1280*720, we can change the fallback resolution that the game currently defaults to. At 0x00e851c0 there is a function in the game that  defines all the starting viewports resolutions. 
![image](https://user-images.githubusercontent.com/42299919/74235804-1f48e180-4cd0-11ea-922f-596fae16c058.png). By changing the values at 0xA84615 (0xE85215) and 0xA8461F (0xE8521F) in the executable (or memory) with your own values you can get proper 1440p.

**Comment by rebtd7** [comment]
Hi there.
Awesome find! It's great to see someone else interested! 

I haven't ever used Ghidra, but it seems to be useful. All I've accomplished so far in this game was using Cheat Engine + Apitrace + PIX for Windows.

I've tried changing the values on RAM but as this seems to be done before the game calls this function and that seems to be tricky. And I wasn't able to change the executable so far (I'm not able to find those instructions opening the .exe, so I assume there's some compression or encryption involved).

Why did you close the issue btw?

**Comment by Banz99** [comment]
Well uhm, I did some more test. It's not doing what it's supposed to. Instead of increasing the rendering viewport, it increases the actual viewport. This is the result:
![image](https://user-images.githubusercontent.com/42299919/74241917-3e9a3b80-4cdd-11ea-9ef7-4f69549748b6.png). I claimed it increased resolution because i also increased the second set of 1280*720 values (that is the viewport where all the 2d stuff is drawn) and for some reason it actually started rendering at 1440p as well, but i don't think anyone would want to play like this:
![image](https://user-images.githubusercontent.com/42299919/74242183-bcf6dd80-4cdd-11ea-9922-18094ed5eb44.png)

**Comment by rebtd7** [comment]
>You should find the addresses in the executable by subtracting 0x401c00 from your addresses in memory.

Nope, at that address 0xA83615 I have a 0x78 byte instead of the expected 0x00 (from the 00 50 00 00). The original .exe is encrypted/obfuscated/compressed somehow. Opening it with Ghidra I get what I believe are the functions that decrypt the contents. One of functions seems to calculate CRC32. That's why I opted to patch everything in memory...

**Comment by Banz99** [comment]
Strange, seems like it's not ()1C00 but only ()C000. You should find it at address 0xA84615.

**Comment by rebtd7** [comment]
Weird. At 0xA84615 I have a 0xC6. Are you using the unmodified executable from Steam?
I'm not able to find the instruction mov [ecx+18],00000500 (searching for bytes C7 41 18 00 05 00 00) anywhere in my .exe,, and decompiling it with Ghidra only shows 6 functions (besides the entry), and one of them seems to be for calculating CRC32.

MD5 of my ffxiiiimg.exe: eddf3e306543fe36b205ecc88e4e18d9

Feel free to add on discord: rebtd7#8605

**Comment by Nucleoprotein** [comment]
I'm sure he is using unwrapped exe, original exe is steamstub wrapped.
