### ISSUE TITLE
Missing libra txt

### ISSUE THREAD

**Issue by eyemessiah** [rebtd7/FF13Fix#14]
Oddly I don't seem to get the libra text even with FF13Fix running.

My INI is default.

I'm running windows 10 with a GTX 1080 TI with recently updated drivers.

Log is:

> [TIME]		[THREAD]	[LOG]
> 13:02:29.214	00014104	FF13Fix 1.4.4 https://github.com/rebtd7/FF13Fix
> 13:02:29.214	00014104	AutoFix for "Final Fantasy XIII" enabled
> 13:02:29.214	00014104	Base Addr = 400000
> 13:02:29.214	00014104	Enabling hooks:
> 13:02:29.214	00014104	initializeHooks = 0
> 13:02:29.214	00014104	Loaded C:\WINDOWS\system32\d3d9.dll
> 13:02:29.214	00014104	createHookDirect3DCreate9 = 0
> 13:02:29.246	00014104	enableHookDirect3DCreate9 = 0
> 13:02:29.246	00014104	createHookCreateWindowExA = 0
> 13:02:29.271	00014104	enableHookCreateWindowExA = 0
> 13:02:29.271	00014104	createHookCreateWindowExW = 0
> 13:02:29.296	00014104	enableHookCreateWindowExW = 0
> 13:02:29.296	00014104	createHookSetWindowLongA = 0
> 13:02:29.320	00014104	enableHookSetWindowLongA = 0
> 13:02:29.321	00014104	createHookSetWindowLongW = 0
> 13:02:29.346	00014104	enableHookSetWindowLongW = 0
> 13:02:29.724	00014104	HWND 0x0003081A: ClassName "OleMainThreadWndClass", WindowName: "OleMainThreadWndName"
> 13:02:31.929	00014104	hkIDirect3D9::GetAdapterIdentifier
> 13:02:31.931	00014104	hkIDirect3D9::Release
> 13:02:32.030	00014104	HWND 0x00040818: ClassName "Static", WindowName: "test"
> 13:02:32.052	00014104	hkIDirect3D9::CreateDevice
> 13:02:32.052	00014104	BehaviorFlags: 00000056 D3DCREATE_FPU_PRESERVE D3DCREATE_HARDWARE_VERTEXPROCESSING D3DCREATE_MULTITHREADED D3DCREATE_PUREDEVICE
> 13:02:32.053	00014104	BackBufferCount: BackBufferCount set to 3
> 13:02:32.053	00014104	PresentationInterval: PresentationInterval set to 1
> 13:02:32.103	00014104	hkIDirect3D9::Release
> 13:02:32.107	00014104	HWND 0x0004081A: ClassName "SQEX.CDev.Engine.Framework.MainWindow", WindowName: ""
> 13:02:32.107	00014104	Starting FFXIII one time RAM patches.
> 13:02:32.135	00014104	hkIDirect3D9::CreateDevice
> 13:02:32.135	00014104	BehaviorFlags: 00000056 D3DCREATE_FPU_PRESERVE D3DCREATE_HARDWARE_VERTEXPROCESSING D3DCREATE_MULTITHREADED D3DCREATE_PUREDEVICE
> 13:02:32.135	00014104	BackBufferCount: BackBufferCount set to 3
> 13:02:32.135	00014104	Changing refresh rate from 60 to 0
> 13:02:32.135	00014104	PresentationInterval: PresentationInterval set to 1
> 13:02:32.179	00014104	HWND 0x0011070C: ClassName "CicMarshalWndClass", WindowName: "CicMarshalWnd"
> 13:02:32.180	00014104	HWND 0x0012070C: ClassName "CicMarshalWndClass", WindowName: "CicMarshalWnd"
> 13:02:32.244	00003388	HWND 0x0002084E: ClassName "D3DProxyWindow", WindowName: "D3DProxyWindow"
> 13:02:32.595	00009036	Loaded C:\WINDOWS\system32\dinput8.dll
> 13:02:32.621	00004960	HWND 0x0003081C: ClassName "DIEmWin", WindowName: "DIEmWin"
> 13:02:32.635	00009036	HWND 0x00020820: ClassName "OleMainThreadWndClass", WindowName: "OleMainThreadWndName"
> 13:02:32.878	00009036	HWND 0x00030820: ClassName "OleMainThreadWndClass", WindowName: "OleMainThreadWndName"
> 13:02:34.109	00012960	NOPing the in-game instruction that sets the frame rate.
> 13:02:34.109	00012960	Removing game slow and synchronous controller continuous controller scanning...
> 13:02:34.109	00012960	Patching libra info box instructions to take in account the game resolution...
> 13:02:34.109	00012960	Enabling controller vibration...
> 13:02:34.109	00012960	Frame pacer target frame rate is at address 185af070
> 13:02:34.109	00012960	Frame pacer disabled.
> 13:02:34.109	00012960	Finished FF13 One Time Fixes
> 13:04:08.072	00014104	HWND 0x000404D2: ClassName "UserAdapterWindowClass", WindowName: ""
> 13:04:08.185	00014104	Unloaded C:\WINDOWS\system32\dinput8.dll
> 13:04:08.185	00014104	Unloaded C:\WINDOWS\system32\d3d9.dll

**Comment by eyemessiah** [comment]
I've tried a variety of resolutions, full screen vs windowed mode, turning DPI scaling on & off, disabling steam overlay etc. with no success.

**Comment by eyemessiah** [comment]
Unless of course libra text *only* appears when you hit the RB - does it not appear when casting libra?

**Comment by rebtd7** [comment]
The text only appear when pressing the button to see the enemy intel in battle

Using intel only reveals more information on that screen

**Comment by eyemessiah** [comment]
Ooops - has been so long since I played.  Working as intended then!!

**Comment by eyemessiah** [comment]
Ooops - has been so long since I played.  Working as intended then!!
