### ISSUE TITLE
Windows Defender question

### ISSUE THREAD

**Issue by ap9999** [rebtd7/FF13Fix#15]
Is it normal for Windows Defender to classify it as a Trojan when I to boot up the game with the fix?

**Comment by rebtd7** [comment]
I'd say it is not normal.

I've tested both 1.4.4 and 1.4.5 on a fully updated Windows 8.1 machine and it doesn't detect anything.

Make sure the file you are using is not altered.

Hashes for version 1.4.5:

FF13_145.zip: 65963FCD8938189605349CAF37878B874F6BD36ABC3FAE5C5DCFEC6E55DF8326
dinput.dll: E848672676E367AE91F3C560D2988AC3EE21D814CB23C764CEEC1115B281B813

**Comment by DamnSynth** [comment]
I'm getting a Windows Defender trojan warning when trying to download 1.4.6 on Windows 10.

**Comment by Nucleoprotein** [comment]
Can you check if that file is also detected? https://github.com/rebtd7/FF13Fix/issues/4#issuecomment-624691455
Maybe it's related to MinHook

**Comment by DamnSynth** [comment]
That file downloads fine. No trojan warning.

**Comment by Nucleoprotein** [comment]
@rebtd7 
Switching to MS Detours can be good idea, they are now on MIT licensed so they are completely free (MS sold them for insane $999 like ~5y ago)
https://github.com/microsoft/Detours

**Comment by Shin741** [comment]
do we have to dl the package ?

**Comment by Nucleoprotein** [comment]
@Shin741 
No, MinHook it's library compiled into OneTweak or FF13Fix, Detours is different library but for same thing, it can be better (or worse).

**Comment by Shin741** [comment]
Bruh I'm lost rn

**Comment by rylabo** [comment]
I just scanned that file, and it's clean. It's the one in ff13fix_146.zip that seems to be the culprit.

**Comment by Nucleoprotein** [comment]
Seems to be false positive, but 2 engines report it:
https://www.virustotal.com/gui/file/095cd25095269d5d33a41163cc0546970dbdd9e6e3f6d80e3486ad110b4cb29a/detection

**Comment by Nucleoprotein** [comment]
False positive, current 1.6.4 is not flagged (yet).

**Comment by ap9999** [comment]
Good to know. Thanks.
