### ISSUE TITLE
Lightning Returns Fix Branch

### ISSUE THREAD

**Issue by MarioTainaka** [rebtd7/FF13Fix#16]
Would you consider making a controller fix for lighting returns?

**Comment by Nucleoprotein** [comment]
If I remember correctly, Lightning Returns uses slightly different engine, so I think most of those fixes can be directly ported to support it, you need to make new ones.

**Comment by MarioTainaka** [comment]
Ah okay. well I do hope one of you considers this in the future. and maybe fixing the asset streaming as well.

**Comment by MarioTainaka** [comment]
Ah okay. well I do hope one of you considers this in the future. and maybe fixing the asset streaming as well.

**Comment by seuvah** [comment]
Again thank you for fix, 60 fps smooth both games finally finished, and left joyfull memories(and no battles vs stutter =) ). If you could fix texture streaming in FFLR that will be great !

**Comment by MarioTainaka** [comment]
I'd be happy to share my exe for Lightning Returns for future use.

**Comment by chrcoluk** [comment]
Mario you fixed LR stuttering issues with asset switching?

**Comment by Surihix** [comment]
Requesting one of the creators to close this issue page as I have already opened an issue detailing most of the problems that the PC port of LR suffers.
https://github.com/rebtd7/FF13Fix/issues/45

**Comment by rebtd7** [comment]
Closing in favor of #45
