### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by NijiBashira** [rebtd7/FF13Fix#2]
The fix is simply not working at all for me : 
- No matter the settings, the enemy info text is still missing. 
- Using these parameters :

> `PresentationInterval = -1
> FFXIIIIngameFrameRateLimit = 45
> FullScreenRefreshRate = 0
> 
> TripleBuffering = true
> SwapEffect = -1
> AlwaysActive = false
> AutoFix = true
> Multisample = 0
> HideCursor = true
> ForceHideCursor = false
> BehaviorFlags = 0`

The framerate still go above the 45 FPS (or any other arbitrary number I try) limit I set (and, incidentally, isn't improved in any way).

- The framerate still clearly caps at 60 even when Vsync is disabled both in the .ini and the GPU Control Panel.

System info :
- Windows 8.1 (Language : French)
- Intel Core i7-4700MQ
- Nvidia GeForce GT 755M

Attached files are FF13Fix logs for both 1.0 and 1.1 (neither of which worked)

[FF13Fix 1.0.log](https://github.com/rebtd7/FF13Fix/files/4015671/FF13Fix.1.0.log)
[FF13Fix 1.1.log](https://github.com/rebtd7/FF13Fix/files/4015672/FF13Fix.1.1.log)

**Comment by Nucleoprotein** [comment]
"Unable to find frame rate pattern. This is normal if the game still hasn't completely started yet."
Patch for framrate limiter etc. from some reason is failing for you, you have modified .exe file in some way?

**Comment by NijiBashira** [comment]
I don't think I have modified the .exe ever. I can't even recall any patch for it existing. I also went through with Steam's file verification before trying FF13Fix (although I only assumed it would revert _all_ potentially modified files to their default state)

**Comment by NijiBashira** [comment]
Finished re-installing, and it's still not working. I don't know what to try anymore.

**Comment by Nucleoprotein** [comment]
I check you log again it look like hooks are failed because you not have any hkIDirect3D9 call in log

```
15:47:09.395	00006196	hkIDirect3D9::GetAdapterIdentifier
15:47:09.398	00006196	hkIDirect3D9::Release
```

Dunno why this happens for you.

**Comment by rebtd7** [comment]
I tried the release on an English Windows 8.1 and I was not able to reproduce the issue =/
Do other things that hook D3D work on your game? (like reshade)
Are you using any other launcher/overlay/wrapper that could be causing something weird to happen?

**Comment by NijiBashira** [comment]
I just tried ReShade for the first time, and it worked flawlessly. I've also used GeDoSaTo very occasionally without issues in the past.

I'm using the default launcher, the only overlay I'm aware of is the Steam overlay (and disabling it doesn't help). I'm not sure what a wrapper is in this case, but I'm not using anything special with or before the game.

**Comment by NijiBashira** [comment]
Following a friend's advice, I tried two things : 

- Booting the game using my laptop's integrated GPU instead of the dedicated GPU
- Generating OneTweakNG logs

Attached are the FF13Fix logs for both versions (running on integrated GPU), and OneTweakNG logs for both the integrated GPU and the dedicated GPU.
[OneTweakNG NVidiaGPU.log](https://github.com/rebtd7/FF13Fix/files/4022233/OneTweakNG.NVidiaGPU.log)
[FF13Fix 1.0.log](https://github.com/rebtd7/FF13Fix/files/4022234/FF13Fix.1.0.log)
[FF13Fix 1.1.log](https://github.com/rebtd7/FF13Fix/files/4022235/FF13Fix.1.1.log)
[OneTweakNG iGPU.log](https://github.com/rebtd7/FF13Fix/files/4022236/OneTweakNG.iGPU.log)

**Comment by NijiBashira** [comment]
After a similar wrapper DLL for another game refused to work, it turns out the issue was being caused by the GPU driver I had, which was three years old. Updating didn't seem to fix the issue, but reverting to an older version from 2015 did, somehow. 

Now it work with a few hiccups : Libra info text doesn't display _at all_, even on 720p; framerate is always capped at 60 in Fullscreen mode, despite disabling VSync everywhere; the Steam overlay doesn't work anymore; enabling Borderless in the .ini forces the game into the highest resolution.

I will now close this issue, and try to see if I can get around those problems, and eventually I'll possibly open new issues for them. I assume (maybe wrongfully) that the last two problems are normal and expected, however.

**Comment by rebtd7** [comment]
Thanks for reporting back
I haven't tested borderless (it is from OneTweakNG and I haven't changed it), but Steam overlay should work fine (at least it works for me and I haven't seeing anyone else reporting this)
