### ISSUE TITLE
Missing controller prompts on 1.4.6

### ISSUE THREAD

**Issue by ukyokuonji** [rebtd7/FF13Fix#21]
I updated to 1.4.6 but I noticed that controller button prompts are now missing. On 1.4.4 they're there. I uploaded some screenshots showing it.
https://imgur.com/a/Fk00wDx

I'm playing at 4K, dunno if that makes a difference

**Comment by Nucleoprotein** [comment]
Works fine for me in 2K, can you give more info? System spec (GPU?)?

**Comment by rebtd7** [comment]
Does this happen consistently on 1.4.6 butnever on 1.4.4?

This is a bug in the original game: https://steamcommunity.com/app/292120/discussions/1/1692659135902978386/

I don't think it is related with the changes done in 1.4.6. Could you please re-test?

**Comment by ukyokuonji** [comment]
So, this is interesting. I accidentally left the prompts on Keyboard Type in the options menu. On 1.4.4 when I use my controller w/ Keyboard Type, console button prompts still show up. On 1.4.6 with Keyboard Type, the prompts disappear. But if I switch to Controller Type on 1.4.6, the prompts show up as normal. I guess there's no real problem!
