### ISSUE TITLE
Windows defender

### ISSUE THREAD

**Issue by Patrick998** [rebtd7/FF13Fix#22]
Is it normal for windows defender to detect the download as a Trojan?

**Comment by ukyokuonji** [comment]
Probably. But the project is legit

**Comment by selingerJosh** [comment]
Windows Security picks up the Wacatac.D!ml trojan I try download 1.4.6. Haven't had this issue with previous versions. Supposedly dinput8.dll is the affected file. Is it a false positive?

**Comment by Nucleoprotein** [comment]
This maybe heuristics, FF13Fix uses function hooking and overwriting process memory - this can be detected as dangerous.

**Comment by seuvah** [comment]
ESET 13 dont report anything. 1.4.6 returned some battle effects in both games BIG thank you.

**Comment by alex732135** [comment]
Is there a way to prevent this? I find that I can boot up the game once, then after that I need to validate files. Windows Defender throws the Trojan warning, but I can't seem to override it.

**Comment by seuvah** [comment]
https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security 

Add game folder and dinput8.dll to exclusion

**Comment by Nucleoprotein** [comment]
Duplicate of #15
