### ISSUE TITLE
Vibration Strength

### ISSUE THREAD

**Issue by kartelusm** [rebtd7/FF13Fix#24]
At first I thought the vibration is not working, but it actually is - it is just very very week. I tested this on a wireless xbox360 controller and Logitech F510 controller (the wired one), same behaviour.

Is there any way to control the vibration strength?

**Comment by hyperspeedgx** [comment]
I can confirm it, i never played the game on consoles though so i dunno if it's the right behavior.

**Comment by kartelusm** [comment]
@hyperspeedgx I did, and I remember it having quite a bit more strength. It was a PS3 version though, so I presume the input is a completely different code.

**Comment by No-One17** [comment]
I thought I was the only one that was thinking about this.

**Comment by Surihix** [comment]
With the fix, the vibration works for both of the games and they feel normal for me. I haven't played the console versions, so I do not know the vibration strength in those versions. 
The controller vibrates, if u r walking near the large adamantoise based enemies in archylte steepe and if u get hit or stagger a group of enemies.
I am guessing the vibration behavior for the PC port is not adjusted to the levels found in the console versions as SE did not even bother to make the game call in the code to vibrate in the PC port, let alone adjust the strength.  
The fix works by calling the DirectInput code that the game uses natively to vibrate and the author of the fix did say there r plans for Xinput support natively, so yeah tht could be a thing in a future version of the fix.

**Comment by Nucleoprotein** [comment]
Nope, vibration code uses XInput already:
https://github.com/rebtd7/FF13Fix/blob/master/d3d9ex/XInputManager.cpp

**Comment by Surihix** [comment]
Oops I misread the authors words on this reddit page to my comment on the vibration. Extremely sorry for tht incorrect reply in this issue page.
https://www.reddit.com/r/FinalFantasy/comments/egxu9c/ff13_pc_unofficial_fixes/fi4uimb?utm_source=share&utm_medium=web2x

So according to tht line in the Xinput manager, vibration strength is adjustable with the fix which is nice. Maybe allowing us to edit the strength in the fix's ini file in a future update would be nice.

**Comment by kartelusm** [comment]
> Maybe allowing us to edit the strength in the fix's ini file in a future update would be nice.

That would be excellent.

**Comment by shinra358** [comment]
FFXIII has this issue. Not FFXIII-2

**Comment by rebtd7** [comment]
Implemented in v1.5.0
