### ISSUE TITLE
Almost

### ISSUE THREAD

**Issue by Sagiri88** [rebtd7/FF13Fix#25]
Please don't give up on this, you are close to saving this great game, from the pass of time.
Im still missing like 3 frames even with all the nvidia inspector settings and this fix.. maybe add a more agressive aproach to disable something, to me the game just caps at 500 mb ram.

**Comment by Nucleoprotein** [comment]
I dont think we can get more FPS, yours hardware is to low i think. For me game runs on quite stable 60FPS

**Comment by Sagiri88** [comment]
yeah, without a way to force the game or give it at least 200 mb more ram, it probably won't. High priority does nothing, also.

**Comment by rebtd7** [comment]
You cannot magically convert RAM into more meaningful FPS numbers, unfortunately. Closing this (we are already improving performance where we can...)
