### ISSUE TITLE
[Feature Request] Ultrawide support

### ISSUE THREAD

**Issue by Nezarn** [rebtd7/FF13Fix#32]
Currently game has black bars when using ultrawide resolutions, proper fullscreen ultrawide would be nice.

**Comment by Keith94** [comment]
This can now be fixed with a mod.

https://community.pcgamingwiki.com/files/file/2017-final-fantasy-xiii-ultrawide-fix/

**Comment by Nucleoprotein** [comment]
We can implement this inside FF13Fix so you will not need two separate fixes.
