### ISSUE TITLE
1.5.1 breaks hunts texts

### ISSUE THREAD

**Issue by danilo-bc** [rebtd7/FF13Fix#43]
I'm playing on linux on a gtx 1650 and the latest DXVK and NVidia stable drivers. To use 1.5.1 I added d3d9 to Wine DLL overrides and I confirmed the game is using the fix by changing the game's framerate (and the game running higher than 60fps)

Release 1.4.6 works fine, with OCCASIONALLY breaking text boxes, but restarting the game fixes it (it can be identified by not having the text box describing the previous actions of the team during a Load Game screen, so it's easily identifiable).

On 1.5.1, however, hunt texts always show up cut out like shown. From 1.4.6 to 1.5.1 the main change for me is the menu performance, it's much better in the current version.

Ignore the black rectangle on the left, that's from my poor screenshotting skills.
![huntbug](https://user-images.githubusercontent.com/7863971/110642985-59660a80-8192-11eb-8238-187d9f9f3b28.png)

**Comment by Nucleoprotein** [comment]
What resolution you use? This can be related to one pixel offset in viewport fix i have added.

**Comment by danilo-bc** [comment]
I'm using 1920x1080, 60 fps ingame framerate, 120fps monitor.

**Comment by Nucleoprotein** [comment]
Disabling SetScissorRect patch fixes some of those so this is definitely something with scissor fix.

**Comment by Nucleoprotein** [comment]
Fixed in e15529e67e9141084f9280d578f3a0a1f1f2bdc3

@rebtd7 can you create new release/hotfix?

**Comment by rebtd7** [comment]
Release 1.5.2 includes the commit above, let us know if the issue is fixed

**Comment by danilo-bc** [comment]
There are still plenty of broken text boxes.

This is the minimap on the mission list
![stillbug1](https://user-images.githubusercontent.com/7863971/110793385-51ba6a80-8253-11eb-94d6-2118b5275034.png)

This is the new hunt text
![stillbug2](https://user-images.githubusercontent.com/7863971/110793494-6f87cf80-8253-11eb-81cd-d141c1f9385b.png)

This is the text on the loading screen
![stillbug3](https://user-images.githubusercontent.com/7863971/110793638-9f36d780-8253-11eb-940a-f9da55a39404.png)

All these are not apparent on 1.4.6

**Comment by danilo-bc** [comment]
I just restarted the game and all the screenshots I've just shown are fixed. I don't understand this type of "time-variance". Maybe switching from 1.4.6 to 1.5.x leaves broken pre-compiled shaders which affect these parts?

**Comment by Nucleoprotein** [comment]
So this is fixed by 1.5.2? Please close issue if it's fixed.

**Comment by danilo-bc** [comment]
I didn't want to close at first because it required two game runs and may be unstable, but it all seems fixed! It's a pretty minor inconvenience.

Thanks a lot!
