### ISSUE TITLE
Persistent jagged lines in 1080p

### ISSUE THREAD

**Issue by Avalanche6** [rebtd7/FF13Fix#46]
There are 2 persistent jagged lines on my screen whenever I play FFXIII, one is horizontal and the other vertical. I don't know if you can see it properly in the picture below, but I placed a red dot at the top left corner where the two lines intersect like a + sign.

![ff13tearing](https://user-images.githubusercontent.com/80547268/110998716-3fbcf280-834d-11eb-9120-62c29dce52de.png)

The problem only persist in the 1920x1080 resolution as I tried the other resolutions and it's perfectly fine.

I tried numerous ways to fix it, but no luck. Changing Fullscreen to Borderless/windowed mode. Turning vsync on and off. Updating my driver. 

I want to mention that the jagged lines disappears whenever I am in the menu screen, during a prerendered cutscene or if I remove the ff13fix files.

My specs are:
Windows 10
Intel i5 4460
Geforce 1060 gtx 6gb

Thank you.

**Comment by Nucleoprotein** [comment]
Check if this file resolves problem:
[d3d9.zip](https://github.com/rebtd7/FF13Fix/files/6133242/d3d9.zip)

**Comment by Avalanche6** [comment]
Yes, the jagged lines are gone.

Thank you a lot!

**Comment by Nucleoprotein** [comment]
Fixed in https://github.com/rebtd7/FF13Fix/commit/2001b949457e536505d205add24b14305df4a76f
