### ISSUE TITLE
Windows 10 requires 32-bit programs to use 4GB patches

### ISSUE THREAD

**Issue by trqf** [rebtd7/FF13Fix#48]
Windows 10 requires 32-bit programs to use 4GB patches, otherwise using reshade or dxvk will cause memory overflow and crash.
(32-thread CPU triggers this problem)
I used this software to solve the problem to a certain extent: https://ntcore.com/?page_id=371

**Comment by rebtd7** [comment]
I suggest using that software to patch FF13-2 to use 4GB, but the same cannot be easily done due to the its stupid DRM. I've tried to work around this but I wasn't successful (yet?).
