### ISSUE TITLE
Enemy intel rect pos doesn't account for aspect ratio

### ISSUE THREAD

**Issue by devXin** [rebtd7/FF13Fix#5]
Playing in a 16:10 resolution, the enemy intel info text isn't displaying correctly. The horizontal pos and size are correct, but it only displays about 2/3 the text vertically (about 2.5 lines instead of all 4).

The game uses a letterbox presentation for non-16:9 resolutions (I actually don't know if the backbuffer is 16:9 or 16:10, but obviously the positioning for the rect isn't correct; I assume the size is fine since the presentation is always 16:9 anyway).

It works as expected in 16:9 resolutions (all 4 lines draw correctly).

Edit: yeah, looking at FF13_FixMissingEnemyScan, it just assumes 16:9, so the rect is getting placed too high on the screen and the text is getting cut off.

**Comment by rebtd7** [comment]
Thanks for the report. Fixed in 1.4.1.

Fun fact that I've found out when fixing this:
If you are playing on, say, 1920x1200, the game will actually render at that resolution. 
Then downscale to 1920x1080, adding the black bars on top and bottom. So you are effectively supersampling on one axis.
