### ISSUE TITLE
Ultrawide Patch Fix for FFXIII: Not Working After Following Instructions

### ISSUE THREAD

**Issue by SheuBox** [rebtd7/FF13Fix#53]
Hi! I am inquiring about some feedback or helpful advice what I may be doing wrong or if there's a technical issue/bug/glitch for me.

So I followed exactly these instructions from @killer-m's "Final Fantasy XIII Ultrawide Fix 1.0.0":
Installation:
Unpack the archive
Copy all files into two game folders
"\FINAL FANTASY XIII\"
"\FINAL FANTASY XIII\white_data\prog\win\bin\"

-- I proceeded to extract my files into my mods directory. Copied them both into the two game folders as instructed, and it didn't remove the black pillar bars from my game.
-- Also another bug I encountered.. I use a Razer Chroma Cynosa keyboard (original) and I can't seem to change the FOV using F5 or F6 or F7 keys.. also changing the readme script file doesn't do anything for me.

Extra notes:
* I use an LG Ultrawide monitor along side a BenQ monitor that I use for multi-monitoring
* I use in conjunction with the HD Textures/Models/Fixes and bugs patch

I would happy to pass along more information if needed. Hopefully this will suffice for now. Thanks to anybody to reads this!

**Comment by SheuBox** [comment]
Apologies everyone. I realized this had nothing to do with the fixes patch I was side tracked. But for anyone interested I used this ultrawide patch from community pc wiki
https://community.pcgamingwiki.com/files/file/2017-final-fantasy-xiii-ultrawide-fix/

My second big issue will be posted separately right now..

**Comment by Surihix** [comment]
I think the ultrawide fix linked in the pcgaming wiki could also be hooking into the game some way or its just outdated and doesn't work properly cause if that.

@rebtd7 If we can add in new updated functions of whatever that ultrawide fix does to a newer version of FF13Fix itself would be great.

**Comment by SheuBox** [comment]
If it's worth mentioning. I purchased off the steam sale a couple days ago, and there's no dinput8.dll anymore. Probably wasn't worth mentioning but yeah.

**Comment by rebtd7** [comment]
Closing as this isn't related to this project
