### ISSUE TITLE
Reshade Preset & Fixes Patch do not work together

### ISSUE THREAD

**Issue by SheuBox** [rebtd7/FF13Fix#54]
Hi. I need help troubleshooting using the Clean Reshade Preset from nexusmods.com/finalfantasy13/mods/15?tab=logs alongside this FF13Fix patch. They both utilize d3d9.dll and unfortunately can't use both to fix the performance issues with having a a great reshade. One person mentioned in the steam community discussions to rename the FF13Fix of them to dxvk.dll but I remembered I could not launch the game with both in the \FINAL FANTASY XIII\white_data\prog\win\bin\ directory.

Any helpful advice will be much appreciated. I also made an off topic post about an ultrawide patch not working.. which I realized right after it had nothing to do with the FF13Fix so sorry for the inconvenience.. but it should be helpful to somebody else too!

Thanks everyone for reading and much appreciative.

**Comment by Surihix** [comment]
Shouldn't the DXVK's d3d9.dll file be renamed to dxvk.dll? 
@rebtd7 we might need an new workaround for using reshade as well.
Can the d3d9.dll file be renamed to ff13fix.dll or something else that doesn't interfere with other similarly named files ?

**Comment by SheuBox** [comment]
Separate note* 

If I want to change vibration strength using the FFXIIIFix.Ini, I would just change the value and save the file right? I tried changing values past 2.000000 but it didn't seem to have any affect either, maybe when I set it to 20.000000 it might've strengthened it a little.. I'm not too sure if I'm just a noob or not, but thought it was worth bringing up too. The positive side is that I 100% noticed there was vibration controller feedback! Just the strengthening values I wasn't too sure on. Thanks again for the read for anybody really appreciate it!

**Comment by SheuBox** [comment]
So update. If I change the Fixes patch to dxvk.dll and the reshade preset to d3d9.dll I'll get the reshade. But doesn't seem to fix the fix performance patch because of the jagged lines/screen tear. Not to mention when I do vise versa (d3d9.dll for fixes patch and dxvk.dll for reshade pack) it will not recognize the reshade pack and I will be left with the reshade program with no preset to acquire and work functional.

**Comment by rebtd7** [comment]
Use 1.6.2 and rename ReShade's DLL to ```ReShade32.dll```.

If the preset are missing, make sure the paths in Reshade.ini are correct.
You may want to change them to be absolute instead of relative.

**Comment by rebtd7** [comment]
Issue is fixed I guess. Feel free to re-open if this isn't the case.
