### ISSUE TITLE
Game not starting.

### ISSUE THREAD

**Issue by GossipYawa** [rebtd7/FF13Fix#56]
Hello! I've tried using version 1.6.2 of the patch but it doesn't work for me. I tried launching the game after placing the two patch files in the correct directory, but I can only get to the launcher. When I press "Start Game" nothing happens.

I tried previous versions of the patch and with some I get the same result. With others, the game does launch, but after seeing the "Square Enix" logo I hear a Windows system error sound and the game stops. It is quite random in which versions "work" and which dont. (I mean, none actually work since I can't get to the game, but you get the point.)

I looked into previous issues posted online and I don't have any overlay installed (Discord, Steam, etc.) and I tried messing with my antivirus settings (I have Malwarebytes) and disabling it altogether but nothing works. When I'm only running Microsoft Defender and I try to launch the game with the patch, the system tells me a file has been blocked. I tell Windows to leave it alone and it's the same thing: I can get to launcher, but not to the actual game.

I took a look at the log and it says: "ERROR: Unable to get attributes of D:\Jeux\Final Fantasy XIII\Final Fantasy XIII\white_data\prog\win\bin\untouched.exe. Does the file exist?"

Seems like the issue but I don't know what to do with that information.

I'm really interested in your work and I desperately need it to get the game running smoothly. My PC is more than capable of running it (GTX 1050) but I still have FPS issues while other games are more than fine. Also, controller vibration is a must-have for me.

Thanks in advance!

[FF13Fix.log](https://github.com/rebtd7/FF13Fix/files/6178038/FF13Fix.log)

**Comment by Nucleoprotein** [comment]
https://github.com/rebtd7/FF13Fix#usage-with-the-4gb-large-address-aware-patch

**Comment by GossipYawa** [comment]
I created the "untouched.exe" file and patched the original with the 4G Patch and I still have the issue.

Here's my update log:
[FF13Fix.log](https://github.com/rebtd7/FF13Fix/files/6178111/FF13Fix.log)

**Comment by Nucleoprotein** [comment]
I think this is caused by https://github.com/rebtd7/FF13Fix/pull/52 but dunno why... investigating

**Comment by GossipYawa** [comment]
Thank you for your time!

**Comment by rebtd7** [comment]
Which version of the game are you using? It doesn't seem you are using an unmodified executable of the game.
Cracked versions are not supported.
