### ISSUE TITLE
FFXIII not launching properly.

### ISSUE THREAD

**Issue by Deefoz** [rebtd7/FF13Fix#59]
I got dxvk and ffxiifix installed, now the game won't launch and It doesn't give me an error. I launch through steam, the ffxiii launcher opens. I have this set to 720 and 2x aliasing with low shadow resolution.

After clicking to launch the game, nothing happens... like it tries, but then just doesn't

What setting would cause this?

GPU: rx5600xt (saphire pulse, with faster bios, running silent bios)
CPU: Ryzen 3700x
16GB ram
crosshair impact x570 mobo

I can post logs later today.

**Comment by Deefoz** [comment]
[FF13Fix.log](https://github.com/rebtd7/FF13Fix/files/6185017/FF13Fix.log)

Here is a log from one of the launch attempts

**Comment by Deefoz** [comment]
[FF13Fix.log](https://github.com/rebtd7/FF13Fix/files/6185039/FF13Fix.log)

**Comment by Deefoz** [comment]
this is with 163 no 4 gb patch with dxvk
[FF13Fix.log](https://github.com/rebtd7/FF13Fix/files/6185092/FF13Fix.log)

**Comment by rebtd7** [comment]
Does the game work without FF13Fix? (just dxvk)

**Comment by Deefoz** [comment]
Yes but the frame rate stutter is unplayable.

**Comment by Deefoz** [comment]
I uninstalled my antivirus just in case. uninstalled and reinstalled the game, installed dxvk and ffxiiifix. 

[FF13Fix.log](https://github.com/rebtd7/FF13Fix/files/6188340/FF13Fix.log)

**Comment by Nucleoprotein** [comment]
Looks like ref count issue...

**Comment by Deefoz** [comment]
I saw this come up somewhere else. It there a work-around?

**Comment by Nucleoprotein** [comment]
There is new PR with possible fix. I'm i work so I can't build it for you
to test

wt., 23 mar 2021, 11:40 użytkownik Deefoz ***@***.***>
napisał:

**Comment by Deefoz** [comment]
I am also at work, so i can't test anything right now either.

**Comment by Nucleoprotein** [comment]
Try binary from new PR: https://github.com/rebtd7/FF13Fix/pull/60

**Comment by Deefoz** [comment]
the d3d9.zip file?

**Comment by Deefoz** [comment]
that launched with significant improvement to the game's fps, still has a stutter that i assume is fixable using the  fix file.

**Comment by rebtd7** [comment]
Using dxvk you'll have some cache stuttering every time there's a new shader effect because it needs to convert and recompile the shader. There's a cache, so I think it should only happen once for each shader.

There's a DXVK fork that does shader compilation asynchronously, but it skips the shader effect while it is being compiled (you'll have some incomplete rendering).

**Comment by Nucleoprotein** [comment]
@Deefoz can you post log file created by that version? I want to check for warnings.

**Comment by Deefoz** [comment]
[FF13Fix.log](https://github.com/rebtd7/FF13Fix/files/6193468/FF13Fix.log)

**Comment by Deefoz** [comment]
Here is the log after i changed settings to make it work better.(dunno if that all shows up) 
[FF13Fix.log](https://github.com/rebtd7/FF13Fix/files/6193967/FF13Fix.log)
