### ISSUE TITLE
Fix not working

### ISSUE THREAD

**Issue by GossipYawa** [rebtd7/FF13Fix#65]
Hello. I can't seem to make the fix work. I have no vibration on my controllers (tested a DS4 and an XBOX One controller, both wirelessly) and hot swapping is still enabled, even though it says it is disabled in the ini file. I can stil turn my controllers on and off while the game is open and the game will still recognize them.

I suspect other fixes are not turned on either.

What's weird is that, looking at the log file, it feels like they should be.

I'm using the full Steam version of the game.

Also, I tried my DS4 with and without DS4Windows. I don't know which way is better. And maybe steam controller setup is messing with all of this.

[FF13Fix.log](https://github.com/rebtd7/FF13Fix/files/6206815/FF13Fix.log)

Edit: Just tested the frame limiter in the ini file and it works. My game runs at 30 or 60 fps depending on what I type. So my only issue must be with the controllers. Probably Steam?

**Comment by rebtd7** [comment]
FF13Fix simply sends vibration commands to the first connected XInput controller. If you have multiple controllers connected, it might send to one you are not using

I've tested the latest version of https://github.com/Ryochan7/DS4Windows (make sure you are emulating an X360 controller, not a DS4), and the Steam Input (Playstation support enabled) and both work fine using bluetooth.  Just make sure you use one or the other, not both together.
I don't own a X1 controller to test it unfortunately, but it should work.

Also, the vibration effects in this game are very subtle. Make sure you are testing some place you know there's vibration. The ray attack of the very first enemy you face in the game causes the controller to vibrate when hit.

**Comment by GossipYawa** [comment]
My controllers were never connected at the same time. And when I use DS4Windows, I am indeed emualting an X360 controller.

Just to make sure: are there any other places towards the beginning of the game where there is vibration? For instance, the opening cutscene?

Also, how am I still able to hotswap controllers while the game is open while it should be disabled?

**Comment by GossipYawa** [comment]
Okay, so I managed to have everything working by... restarting my computer...

Yep. the classic.

Tested both my X1 controller and DS4 and they both have vibration. But you're right, it's veeeeeeeeeeeeeery subtle. Even more so on the DS4.

Thanks anyway!
