### ISSUE TITLE
FFXIII-2 stutters alot with DXVK in high end rig.

### ISSUE THREAD

**Issue by Heavenskies11** [rebtd7/FF13Fix#66]
I installed this by following the guide but my game stutters alot. I'm using every fix showed. I know vulkan save part of the graphic load in the disk (Cache? I believe) that's why it stutters and the perfomance should be better after a few minutes (no problems with other DXVK games like GTA IV) but with FF 13-2 it stutters in every escenario like spawning creatures, navigating to a new map era. It's fixed after a few minutes after the whole map or level is already loaded. But when I restart the game and I visit the same places the stutters come back. Is this a normal behaviour? 

This is how the files from the guide are installed in the folder 
I don't know if i'm doing something wrong. 

Files attached 

Thanks for making this possible btw! 

Nvidia gtx 1660 ti
Ryzen 5 2700x
16gb ram
![Screenshot002](https://user-images.githubusercontent.com/81504515/112744549-3f804200-8f5e-11eb-9aef-fd8d23d3145c.png)

**Comment by dlshinobi** [comment]
Oh yes, FFXIII-2 stutters alot with DXVK!!!

My only solution:
1) Download / Use **dxvk-async** from https://github.com/Sporif/dxvk-async/releases
2) Go to the game directory "../alba_data/prog/win/bin" and create file "**dxvk.conf**".
The content of **dxvk.conf** file should look like this:
dxvk.enableStateCache = False
dxvk.enableAsync = True

P.S. Now it is possible to play, but **async** has a negative effect.

**Comment by rebtd7** [comment]
@Heavenskies11 Is there any reason you are using dxvk on Windows with an Nvidia card?
