### ISSUE TITLE
The game crashes if I stream it from Discord

### ISSUE THREAD

**Issue by D4rKR420R** [rebtd7/FF13Fix#72]
Hello, I recently tried out your fix and I realized, after a couple of days of playing it with no issues, when I try to stream it from Discord, the game suddenly crashes. I am using a Windows 10 operating system.

**Comment by Nucleoprotein** [comment]
Please upload log file.

**Comment by D4rKR420R** [comment]
> Please upload log file.

Hi. For some reason, I can no longer reproduce this bug anymore. I noticed my Windows somehow reset some things after accidentally switching users. I'll report back if this happens again.
